config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :omniauth_callbacks => :omniauth_callbacks
  }

  if Rails.env.development? || Rails.env.staging?
    get "dev_login/:id", controller: 'pages', action: 'dev_login'
  end

  resources :users do
    resources :notifications, shallow: true
    member do
      post :follow
      post :unfollow
    end
  end

  resources :inquiries, only: [:new, :create, :show]
  resources :spaces
  resources :reservations

  resources :subscriptions

  resources :payments do
    collection do
      post 'paid_users', to: 'payments#post_paid_users'
      post "rnoti", :to => "payments#rnoti"
      get 'result', :to => "payments#result"
    end
  end

  # tmp 
  get 'confirmation_instructions', :to => "mails#confirmation_instructions"
  get 'email_changed', :to => "mails#email_changed"
  get 'password_change', :to => "mails#password_change"
  get 'reset_password_instructions', :to => "mails#reset_password_instructions"
  get 'unlock_instructions', :to => "mails#unlock_instructions"
  get 'program_accepted', :to => "mails#program_accepted"


  # my pages
  get 'my/inquiries'

  # static pages
  get 'pages/terms'
  get 'pages/privacy'

  root 'pages#home'

  namespace :admin, path: 'radmin' do
    root 'subscriptions#index'

    get 'base-style', :to => "pages#base_style"


    resources :users do
      collection do
        get :hibernated
      end
    end
    resources :notifications
    resources :subscriptions
    resources :user_deletions

    resources :inquiries

    resources :spaces do
      member do
        get :delete_file
      end
    end
    resources :reservations

    resources :boards
    resources :board_posts do
      resources :comments, module: :board_posts
    end

    resources :payments do
      get 'edit_cancel_status'
    end

    resources :op_items
    resources :policies
    resources :roles
    resources :settings
    resources :assets, only: [:create, :destroy]

    if Rails.env.development? || Rails.env.staging?
      require 'sidekiq/web'
      require 'sidekiq/cron/web'
      mount Sidekiq::Web => '/sidekiq'
      mount LetterOpenerWeb::Engine, at: "/emails"
    end
  end
end

app/views/admin/_admin_sidebar.html.haml
.col-md-3.col-xl-2.bd-sidebar
  %form.bd-search.d-flex.align-items-center{:role => "search"}
    %span.algolia-autocomplete{:style => "position: relative; display: inline-block; direction: ltr;"}
      %input#search-input.form-control.ds-input{"aria-autocomplete" => "list", "aria-expanded" => "false", "aria-label" => "Search for...", "aria-owns" => "algolia-autocomplete-listbox-0", :autocomplete => "off", "data-docs-version" => "4.4", :dir => "auto", :placeholder => "Search...", :role => "combobox", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "search"}/
      %pre{"aria-hidden" => "true", :style => "position: absolute; visibility: hidden; white-space: pre; font-family: -apple-system, system-ui, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: normal; text-indent: 0px; text-rendering: auto; text-transform: none;"}
      %span#algolia-autocomplete-listbox-0.ds-dropdown-menu{:role => "listbox", :style => "position: absolute; top: 100%; z-index: 100; display: none; left: 0px; right: auto;"}
        .ds-dataset-1
    %button.btn.btn-link.bd-search-docs-toggle.d-md-none.p-0.ml-3.collapsed{"aria-controls" => "bd-docs-nav", "aria-expanded" => "false", "aria-label" => "Toggle docs navigation", "data-target" => "#bd-docs-nav", "data-toggle" => "collapse", :type => "button"}
      %svg{:focusable => "false", :height => "30", :role => "img", :viewbox => "0 0 30 30", :width => "30", :xmlns => "http://www.w3.org/2000/svg"}
        %title Menu
        %path{:d => "M4 7h22M4 15h22M4 23h22", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-miterlimit" => "10", "stroke-width" => "2"}
  %nav#bd-docs-nav.bd-links.collapse{"aria-label" => "Main navigation", :style => ""}
    - if can? :manage, OpItem
      .bd-toc-item.active
        %a.bd-toc-link{:href => "/docs/4.4/getting-started/introduction/"}
          메인 페이지 관리
        %ul.nav.bd-sidenav
          - Setting.op_items.keys.each do |k|
            %li
              = link_to Setting.op_items[k]["name"], admin_op_items_path(category: k)
    - if can? :manage, User
      .bd-toc-item.active
        %a.bd-toc-link{:href => admin_users_path}
          회원 관리
        %ul.nav.bd-sidenav
          %li
            = link_to '전체 회원', admin_users_path
          %li
            = link_to '웹알림', admin_notifications_path
          %li
            = link_to '휴면 회원', hibernated_admin_users_path
          %li
            = link_to '탈퇴 기록', admin_user_deletions_path

    - if can? :manage, Inquiry
      .bd-toc-item.active
        %a.bd-toc-link{:href => admin_inquiries_path}
          상담 관리
        %ul.nav.bd-sidenav
          %li
            = link_to '상담 목록', admin_inquiries_path
    
    - if can? :manage, Subscription
      .bd-toc-item.active
        %a.bd-toc-link{:href => admin_inquiries_path}
          구독자 관리
        %ul.nav.bd-sidenav
          %li
            = link_to '구독자', admin_subscriptions_path
    - if can? :manage, Space
      .bd-toc-item.active
        %a.bd-toc-link{:href => admin_inquiries_path}
          공간 관리
        %ul.nav.bd-sidenav
          %li
            = link_to '공간 관리', admin_spaces_path
          %li
            = link_to '대관 일정 관리', admin_reservations_path
    - if can? :manage, Board
      .bd-toc-item.active
        %a.bd-toc-link{:href => admin_boards_path}
          게시판 관리
        %ul.nav.bd-sidenav
          %li
            = link_to '게시판 관리', admin_boards_path
          %li
            = link_to '게시물 관리', admin_board_posts_path
    - if can? :manage, Policy
      .bd-toc-item.active
        %a.bd-toc-link{:href => admin_policies_path(category: 'terms')}
          약관 및 정책 관리
        %ul.nav.bd-sidenav
          %li
            = link_to '서비스 이용 약관 관리', admin_policies_path(category: 'terms')
          %li
            = link_to '개인정보처리방침 관리', admin_policies_path(category: 'privacy')
    - if can? :manage, Setting
      .bd-toc-item.active
        %a.bd-toc-link{:href => admin_roles_path}
          설정 관리
        %ul.nav.bd-sidenav
          %li
            = link_to '권한', admin_roles_path
          %li
            = link_to '설정', admin_settings_path
            

app/views/admin/_menu.haml
%nav.col-md-2.d-none.d-md-block.bg-light.sidebar.border-right
  .sidebar-sticky
    %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
      %span 메인 페이지 관리

    %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
      %span 회원 관리
    %ul.nav.flex-column
      %li.nav-item
        = link_to '전체 회원 현황', admin_users_path, class: 'nav-link'
      %li.nav-item
        = link_to '구독자', admin_subscriptions_path, class: 'nav-link'

    %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
      %span 공간 관리

    %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
      %span 프로그램 관리

    %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
      %span 약관 및 정책 관리
    %ul.nav.flex-column
      %li.nav-item
        = link_to '서비스 이용 약관 관리', admin_policies_path(category: 'terms'), class: "nav-link"
      %li.nav-item
        = link_to '개인정보처리방침 관리', admin_policies_path(category: 'privacy'), class: "nav-link"

app/views/admin/_menu.html.haml
%nav.col-md-2.d-none.d-md-block.sidebar
  .sidebar-sticky
    %div.div-sidebar
      - if can? :manage, OpItem
        %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
          %span.menu-group-title 메인 페이지 관리
        %ul.nav.flex-column
          - Setting.op_items.keys.each do |k|
            %li.nav-item.px-4.py-1
              = link_to Setting.op_items[k]["name"], admin_op_items_path(category: k), class: 'nav-link'
    
    %div.div-sidebar
      - if can? :manage, User
        %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
          %span.menu-group-title 회원 관리
        %ul.nav.flex-column
          %li.nav-item.px-4.py-1
            = link_to '전체 회원', admin_users_path, class: 'nav-link'
          %li.nav-item.px-4.py-1
            = link_to '웹알림', admin_notifications_path, class: 'nav-link'
          %li.nav-item.px-4.py-1
            = link_to '휴면 회원', hibernated_admin_users_path, class: 'nav-link'
          %li.nav-item.px-4.py-1
            = link_to '탈퇴 기록', admin_user_deletions_path, class: 'nav-link'

    %div.div-sidebar
      - if can? :manage, Inquiry
        %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
          %span.menu-group-title 상담 관리
        %ul.nav.flex-column
          %li.nav-item.px-4.py-1
            = link_to '상담 목록', admin_inquiries_path, class: 'nav-link'

    %div.div-sidebar
      - if can? :manage, Subscription
        %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
          %span.menu-group-title 구독자 관리
        %ul.nav.flex-column
          %li.nav-item.px-4.py-1
            = link_to '구독자', admin_subscriptions_path, class: 'nav-link'

    %div.div-sidebar
      - if can? :manage, Space
        %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
          %span.menu-group-title 공간 관리
        %ul.nav.flex-column
          %li.nav-item.px-4.py-1
            = link_to '공간 관리', admin_spaces_path, class: "nav-link"
          %li.nav-item.px-4.py-1
            = link_to '대관 일정 관리', admin_reservations_path, class: "nav-link"

    %div.div-sidebar
      %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
        %span.menu-group-title 프로그램 관리

    %div.div-sidebar
      - if can? :manage, Board
        %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
          %span.menu-group-title 게시판 관리
        %ul.nav.flex-column
          %li.nav-item.px-4.py-1= link_to '게시판 관리', admin_boards_path, class: "nav-link"
          %li.nav-item.px-4.py-1= link_to '게시물 관리', admin_board_posts_path, class: "nav-link"

    %div.div-sidebar
      - if can? :manage, Policy
        %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
          %span.menu-group-title 약관 및 정책 관리
        %ul.nav.flex-column
          %li.nav-item.px-4.py-1
            = link_to '서비스 이용 약관 관리', admin_policies_path(category: 'terms'), class: "nav-link"
          %li.nav-item.px-4.py-1
            = link_to '개인정보처리방침 관리', admin_policies_path(category: 'privacy'), class: "nav-link"

    - if can? :manage, Setting
      %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-3.mb-1.text-muted
        %span.menu-group-title 설정 관리
      %ul.nav.flex-column
        %li.nav-item.px-4.py-1
          = link_to '권한 관리', admin_roles_path, class: "nav-link"
        %li.nav-item.px-4.py-1
          = link_to '설정 관리', admin_settings_path, class: "nav-link"

app/views/admin/_page_header.html.haml
.jumbotron.m-0
  .d-flex.justify-content-between.align-items-center
    %h1.display-5.flex-grow-1=title
    %div= action
  %div.div-hr