config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :omniauth_callbacks => :omniauth_callbacks
  }

  if Rails.env.development? || Rails.env.staging?
    get "dev_login/:id", controller: 'pages', action: 'dev_login'
  end

  resources :users do
    resources :notifications, shallow: true
    member do
      post :follow
      post :unfollow
    end
  end

  resources :inquiries, only: [:new, :create, :show]
  resources :spaces
  resources :reservations

  resources :subscriptions

  resources :payments do
    collection do
      post 'paid_users', to: 'payments#post_paid_users'
      post "rnoti", :to => "payments#rnoti"
      get 'result', :to => "payments#result"
    end
  end

  # tmp 
  get 'confirmation_instructions', :to => "mails#confirmation_instructions"
  get 'email_changed', :to => "mails#email_changed"
  get 'password_change', :to => "mails#password_change"
  get 'reset_password_instructions', :to => "mails#reset_password_instructions"
  get 'unlock_instructions', :to => "mails#unlock_instructions"
  get 'program_accepted', :to => "mails#program_accepted"


  # my pages
  get 'my/inquiries'

  # static pages
  get 'pages/terms'
  get 'pages/privacy'

  root 'pages#home'

  namespace :admin, path: 'radmin' do
    root 'subscriptions#index'

    get 'base-style', :to => "pages#base_style"


    resources :users do
      collection do
        get :hibernated
      end
    end
    resources :notifications
    resources :subscriptions
    resources :user_deletions

    resources :inquiries

    resources :spaces do
      member do
        get :delete_file
      end
    end
    resources :reservations

    resources :boards
    resources :board_posts do
      resources :comments, module: :board_posts
    end

    resources :payments do
      get 'edit_cancel_status'
    end

    resources :op_items
    resources :policies
    resources :roles
    resources :settings
    resources :assets, only: [:create, :destroy]

    if Rails.env.development? || Rails.env.staging?
      require 'sidekiq/web'
      require 'sidekiq/cron/web'
      mount Sidekiq::Web => '/sidekiq'
      mount LetterOpenerWeb::Engine, at: "/emails"
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :categories
  has_many :posts

  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true, format: { with: /\A[a-z0-9_]+\Z/, message: I18n.t('msgs.error.allowed_only_lower_case') }

  default_scope { order("id desc") }
end

app/models/board/category.rb
class Board::Category < ApplicationRecord
end

app/models/board/post.rb
class Board::Post < ApplicationRecord
  include Commentable

  belongs_to :board

  acts_as_taggable_on :tags

  validates :board, presence: true
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < AdminController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to edit_admin_board_path(@board), notice: I18n.t('msgs.success.saved')
    else
      render :new
    end
  end

  def update
    if @board.update(board_params)
      redirect_to edit_admin_board_path(@board), notice: I18n.t('msgs.success.saved')
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to admin_boards_path, notice: I18n.t('msgs.success.destroyed')
  end

  private

    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(
        :name, :slug,
        categories_attributes: [:id, :seq, :name, :slug, :_destroy],
      )
    end
end

app/views/admin/boards/_category_fields.html.haml
.nested_fields.list-group-item
  .row
    .col-1
      = f.number_field :seq, placeholder: '순서', class: 'form-control'
    .col-5
      = f.text_field :name, placeholder: '분류명', class: 'form-control'
    .col-4
      = f.text_field :slug, placeholder: '영문주소', class: 'form-control'
    .col-2
      = link_to_remove_association "삭제", f, class: 'btn btn-outline-danger btn-block'

app/views/admin/boards/_form.html.haml
= simple_form_for [:admin, @board] do |f|
  .p-4.border-bottom
    %h4.pb-2 기본 정보
    = f.input :name
    = f.input :slug

  .categories.p-4.border-bottom
    %h4.pb-2 분류
    #categories-items.list-group
      = f.fields_for :categories do |category|
        = render 'category_fields', f: category
      .form-group.p-2
        = link_to_add_association '항목 추가', f, :categories

  .p-4
    .form-group
      = f.submit class: 'btn btn-primary'
      = link_to '취소', admin_boards_path, class: 'btn btn-outline-secondary'

app/views/admin/boards/edit.html.haml
= render 'page_header', title: '게시판 > 게시판 수정', action: link_to('목록으로', admin_boards_path, class: 'btn btn-primary')

= render 'form'

app/views/admin/boards/index.html.haml
= render 'page_header', title: '게시판', action: link_to('게시판 추가하기', new_admin_board_path, class: 'btn btn-primary') if can? :create, Board

.p-4
  .pb-4
    %h4 게시판

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th ID
        %th slug
        %th 이름
        %th
    %tbody
      - @boards.each do |board|
        %tr[board]
          %td= board.id
          %td= board.slug
          %td= board.name
          %td.text-nowrap
            = link_to '수정', edit_admin_board_path(board), class: 'btn btn-outline-primary btn-sm'
            = link_to '삭제', admin_board_path(board), method: :delete, class: 'btn btn-outline-danger btn-sm' if can? :destroy, Board

app/views/admin/boards/new.html.haml
= render 'page_header', title: '게시판 > 게시판 추가', action: link_to('목록으로', admin_boards_path, class: 'btn btn-primary')

= render 'form'

app/views/admin/boards/show.html.haml
= render 'page_header', title: "게시판 > #{@board.name}", action: link_to('목록으로', admin_boards_path, class: 'btn btn-primary')