config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :omniauth_callbacks => :omniauth_callbacks
  }

  if Rails.env.development? || Rails.env.staging?
    get "dev_login/:id", controller: 'pages', action: 'dev_login'
  end

  resources :users do
    resources :notifications, shallow: true
    member do
      post :follow
      post :unfollow
    end
  end

  resources :inquiries, only: [:new, :create, :show]
  resources :spaces
  resources :reservations

  resources :subscriptions

  resources :payments do
    collection do
      post 'paid_users', to: 'payments#post_paid_users'
      post "rnoti", :to => "payments#rnoti"
      get 'result', :to => "payments#result"
    end
  end

  # tmp 
  get 'confirmation_instructions', :to => "mails#confirmation_instructions"
  get 'email_changed', :to => "mails#email_changed"
  get 'password_change', :to => "mails#password_change"
  get 'reset_password_instructions', :to => "mails#reset_password_instructions"
  get 'unlock_instructions', :to => "mails#unlock_instructions"
  get 'program_accepted', :to => "mails#program_accepted"


  # my pages
  get 'my/inquiries'

  # static pages
  get 'pages/terms'
  get 'pages/privacy'

  root 'pages#home'

  namespace :admin, path: 'radmin' do
    root 'subscriptions#index'

    get 'base-style', :to => "pages#base_style"


    resources :users do
      collection do
        get :hibernated
      end
    end
    resources :notifications
    resources :subscriptions
    resources :user_deletions

    resources :inquiries

    resources :spaces do
      member do
        get :delete_file
      end
    end
    resources :reservations

    resources :boards
    resources :board_posts do
      resources :comments, module: :board_posts
    end

    resources :payments do
      get 'edit_cancel_status'
    end

    resources :op_items
    resources :policies
    resources :roles
    resources :settings
    resources :assets, only: [:create, :destroy]

    if Rails.env.development? || Rails.env.staging?
      require 'sidekiq/web'
      require 'sidekiq/cron/web'
      mount Sidekiq::Web => '/sidekiq'
      mount LetterOpenerWeb::Engine, at: "/emails"
    end
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < AdminController
  def index
    @users = User.all
    @users = @users.where(role: params[:role]) if params[:role].present?
  end
end

app/views/admin/roles/index.html.haml
= render 'page_header', title: '권한 관리', action: nil

%section.p-4
  %section.mb-4.d-flex.justify-content-between.align-items-center
    %h5 회원
    %div
      = form_with url: admin_roles_path, local: true, method: :get, class: "form-inline" do |f|
        %label.mr-2 권한
        = select_tag :role, options_for_select(User.roles.keys, params[:role]), { include_blank: "전체", onchange: "this.form.submit();", class: "form-control form-control-sm" }

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th ID
        %th 아이디
        %th 이메일
        %th 이름
        %th 권한
        %th
    %tbody
      - @users.each do |user|
        = form_with model: user, url: admin_user_path(user) do |f|
          %tr[user]
            %td= user.id
            %td= user.uid
            %td= user.email
            %td= user.name
            %td
              = f.select :role, User.roles.keys, {}, { class: "form-control form-control-sm" }
            %td.text-nowrap
              = f.submit "저장", class: 'btn btn-outline-secondary btn-sm'