config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :omniauth_callbacks => :omniauth_callbacks
  }

  if Rails.env.development? || Rails.env.staging?
    get "dev_login/:id", controller: 'pages', action: 'dev_login'
  end

  resources :users do
    resources :notifications, shallow: true
    member do
      post :follow
      post :unfollow
    end
  end

  resources :inquiries, only: [:new, :create, :show]
  resources :spaces
  resources :reservations

  resources :subscriptions

  resources :payments do
    collection do
      post 'paid_users', to: 'payments#post_paid_users'
      post "rnoti", :to => "payments#rnoti"
      get 'result', :to => "payments#result"
    end
  end

  # tmp 
  get 'confirmation_instructions', :to => "mails#confirmation_instructions"
  get 'email_changed', :to => "mails#email_changed"
  get 'password_change', :to => "mails#password_change"
  get 'reset_password_instructions', :to => "mails#reset_password_instructions"
  get 'unlock_instructions', :to => "mails#unlock_instructions"
  get 'program_accepted', :to => "mails#program_accepted"


  # my pages
  get 'my/inquiries'

  # static pages
  get 'pages/terms'
  get 'pages/privacy'

  root 'pages#home'

  namespace :admin, path: 'radmin' do
    root 'subscriptions#index'

    get 'base-style', :to => "pages#base_style"


    resources :users do
      collection do
        get :hibernated
      end
    end
    resources :notifications
    resources :subscriptions
    resources :user_deletions

    resources :inquiries

    resources :spaces do
      member do
        get :delete_file
      end
    end
    resources :reservations

    resources :boards
    resources :board_posts do
      resources :comments, module: :board_posts
    end

    resources :payments do
      get 'edit_cancel_status'
    end

    resources :op_items
    resources :policies
    resources :roles
    resources :settings
    resources :assets, only: [:create, :destroy]

    if Rails.env.development? || Rails.env.staging?
      require 'sidekiq/web'
      require 'sidekiq/cron/web'
      mount Sidekiq::Web => '/sidekiq'
      mount LetterOpenerWeb::Engine, at: "/emails"
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  attr_encrypted :ssn, :key => 'secret key', :mode => :per_attribute_iv_and_salt

  # belongs_to :product
  has_many :transactions

  validates :tid, uniqueness: true
  validates :price, :tid, :result_code, :nickname, :payment_type, presence: true
  validate :check_validate_price

  scope :except_cancel, -> { where("is_cancel IS NULL OR is_cancel = ?", false)}
  scope :temporary, -> { where(payment_type: 'temporary') }
  scope :seedmoney, -> { where(payment_type: 'seedmoney') }

  def check_validate_price
    if payment_type == "seedmoney" && price != Anniversary.unscoped.find(anniversary_id).contribution
      errors.add(:base, "결제 금액이 올바르지 않습니다. 관리자에게 문의하세요.")
    end
  end

  def add_fail_error
    errors.add(:base, "결제에 실패했습니다. 결제정보를 다시 확인해주세요.")
  end
end

app/controllers/admin/payments_controller.rb
class Admin::PaymentsController < AdminController
  def edit_cancel_status
    payment = Payment.find params[:payment_id]
    payment.is_cancel = !(payment.is_cancel)
    payment.save

    redirect_to admin_user_path(User.find(params[:user_id]))
  end

  def index
    if params[:filter].present?
      @payments = Payment.where(payment_type: params[:filter]).order('created_at DESC').page(params[:page]).per(10)
    end
  end
end

app/controllers/payments_controller.rb
require 'csv'

class PaymentsController < ApplicationController
  # skip_before_filter :verify_authenticity_token

  def new
    @anniversary = Anniversary.unscoped.find params[:anniversary_id]

    if browser.mobile? || browser.tablet?
      @bank_helper = BankHelper.create
    else
      @bank_helper = BankHelper.new
    end
  end

  def create
    if browser.mobile?
      @transaction = Transaction.build_transaction_mobile( params )
      # logger.info Transaction.build_transaction_mobile( params )
    else
      @transaction = Transaction.build_transaction( params )
      # logger.info Transaction.build_transaction( params )
    end

    if @transaction.payment_type == "seedmoney"
      @payment = Payment.new(price: @transaction.price,
                              anniversary_id: @transaction.anniversary_id,
                              tid: @transaction.tid,
                              result_code: @transaction.result_code,
                              payment_type: @transaction.payment_type,
                              nickname: current_user.nickname)
      unless @payment.save
        render 'new'
        return
      end

      anniversary = Anniversary.unscoped.find(@payment.anniversary_id)
      anniversary.update(has_seedmoney_payment: true)
      user = @payment.anniversary.user
      user.update(role: "sponsor")
    elsif @transaction.payment_type == "temporary"
      @payment = Payment.create(price: @transaction.price,
                                anniversary_id: @transaction.anniversary_id,
                                tid: @transaction.tid,
                                result_code: @transaction.result_code,
                                payment_type: @transaction.payment_type,
                                nickname: @transaction.nickname,
                                bill_name: @transaction.bill_name,
                                bill_address: @transaction.bill_address,
                                bill_phone: @transaction.bill_phone,
                                ssn: @transaction.ssn,
                                buyeremail: @transaction.buyeremail
                                )
    end
    @transaction.payment_id = @payment.id

    if @transaction.save
      if @transaction.result_code == "00"
        redirect_to @payment
      else
        @payment.add_fail_error
        render 'new'
      end
    else
      render 'new'
    end
  end

  def show
    @payment = Payment.find params[:id]
  end

  # 모바일 신용카드, 모바일결제 callback
  def post_paid_users
    if(params[:P_TID] == "")
      @payment = Payment.new
      @payment.add_fail_error

      render 'new'
      return
      # params[:P_RMESG1].force_encoding("EUC-KR").encode("UTF-8")
    end

    # request url로 결제 요청
    uri = URI.parse(params[:P_REQ_URL])
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Post.new(uri.request_uri)
    request.set_form_data({ "P_TID" => params[:P_TID], "P_MID" => ENV['INICIS_MID'] })
    resp = http.request(request)
    result_str = resp.body.to_s.force_encoding("EUC-KR").encode("UTF-8").tr(" ", "")
    logger.info result_str.tr("\n", "")
    @result = CGI::parse(result_str.tr("\n", ""))

    # create transaction
    t = Transaction.new
    # p_noti = CGI::parse( @result["P_NOTI"][0] )
    p_noti = @result["P_NOTI"][0].split(",")
    anniversary_id = p_noti[0].split("=")
    payment_type = p_noti[1].split("=")
    bill_name = p_noti[2].split("=")
    bill_phone = p_noti[3].split("=")
    bill_address = p_noti[4].split("=")
    ssn = p_noti[5].split("=")
    buyeremail = p_noti[6].split("=")

    t.tid = @result["P_TID"][0]
    t.result_code = @result["P_STATUS"][0]
    t.result_msg = @result["P_RMESG1"][0] + @result["P_RMESG2"][0]
    t.pay_method = @result["P_TYPE"][0]
    t.moid = @result["P_OID"][0]
    t.price = @result["P_AMT"][0]
    t.pay_at = @result["P_AUTH_DT"][0]
    t.card_code = @result["P_FN_CD1"][0]
    t.vact_num = @result["P_VACT_NUM"][0]
    t.vact_bank_code = @result["P_VACT_BANK_CODE"][0]
    t.vact_date = @result["P_VACT_DATE"][0]
    t.vact_input_name = @result["P_VACT_NAME"][0]
    t.vact_name = @result["P_VACT_NAME"][0]
    # t.payment_id =
    t.anniversary_id = anniversary_id[1]
    t.nickname = @result["P_UNAME"][0]
    t.payment_type = payment_type[1]

    t.p_vact_time = @result["P_VACT_TIME"][0]
    t.p_auth_no = @result["P_AUTH_NO"][0]
    t.p_rmesg2 = @result["P_RMESG2"][0]
    t.p_noti = @result["P_NOTI"][0]
    #mtrn.p_next_url = @result["P_NEXT_URL"][0]
    #mtrn.p_mname = @result["P_MNAME"][0]
    #mtrn.p_noteurl = @result["P_NOTEURL"][0]
    t.p_card_issuer_code = @result["P_CARD_ISSUER_CODE"][0]
    t.p_card_num = @result["P_CARD_NUM"][0]
    t.p_card_member_num = @result["P_CARD_MEMBER_NUM"][0]
    t.p_card_purchase_code = @result["P_CARD_PURCHASE_CODE"][0]
    t.p_card_prtc_code = @result["P_CARD_PRTC_CODE"][0]
    t.bill_name = bill_name[1]
    t.bill_address = bill_address[1]
    t.bill_phone = bill_phone[1]
    t.ssn = ssn[1]
    t.buyeremail = buyeremail[1]

    t.save

    # payment create
    if payment_type[1] == "seedmoney"
      @payment = Payment.create(price: t.price,
                                anniversary_id: t.anniversary_id,
                                tid: t.tid,
                                result_code: t.result_code,
                                payment_type: t.payment_type,
                                nickname: t.nickname)
      anniversary = Anniversary.unscoped.find(@payment.anniversary_id)
      anniversary.update(has_seedmoney_payment: true)
      user = @payment.anniversary.user
      user.update(role: "sponsor")
    elsif payment_type[1] == "temporary"
      @payment = Payment.create(price: t.price,
                                anniversary_id: t.anniversary_id,
                                tid: t.tid,
                                result_code: t.result_code,
                                payment_type: t.payment_type,
                                nickname: t.nickname,
                                bill_name: t.bill_name,
                                bill_address: t.bill_address,
                                bill_phone: t.bill_phone,
                                ssn: t.ssn,
                                buyeremail: t.buyeremail,
                                )
    end
    t.payment_id = @payment.id

    if t.save
      if t.result_code == "00"
        redirect_to @payment
      else
        @payment.add_fail_error
        render 'new'
      end
    else
      logger.info t.errors
      render 'new'
    end
  end

  def rnoti
    # inicis에서 넘어온 Parameter 저장하기
    # clientip = request.env["REMOTE_ADDR"]
    # if clientip == "211.219.96.165" or clientip == "118.129.210.25"
    t = Transaction.new

    p_noti = params["P_NOTI"].force_encoding("EUC-KR").encode("UTF-8").split(",")
    anniversary_id = p_noti[0].split("=")
    payment_type = p_noti[1].split("=")
    bill_name = p_noti[2].split("=")
    bill_phone = p_noti[3].split("=")
    bill_address = p_noti[4].split("=")
    ssn = p_noti[5].split("=")
    buyeremail = p_noti[6].split("=")
    helper_id = p_noti[7].split("=")

    t.tid = params[:P_TID]
    t.pay_at = params[:P_AUTH_DT]
    t.result_code = params[:P_STATUS]
    t.pay_method = params[:P_TYPE]
    t.moid = params[:P_OID]
    t.price = params[:P_AMT]
    t.nickname = params[:P_UNAME].force_encoding("EUC-KR").encode("UTF-8")
    t.result_msg = params[:P_RMESG1].force_encoding("EUC-KR").encode("UTF-8")
    t.p_rmesg2 = params[:P_RMESG2].force_encoding("EUC-KR").encode("UTF-8")
    t.anniversary_id = anniversary_id[1]
    t.payment_type = payment_type[1]
    t.bill_name = bill_name[1]
    t.bill_phone = bill_phone[1]
    t.bill_address = bill_address[1]
    t.ssn = ssn[1]
    t.buyeremail = buyeremail[1]
    t.helper_id = helper_id[1]

    t.save

    if payment_type[1] == "seedmoney"
      @payment = Payment.create(price: t.price,
                                anniversary_id: t.anniversary_id,
                                tid: t.tid,
                                result_code: t.result_code,
                                payment_type: t.payment_type,
                                nickname: t.nickname,
                                helper_id: t.helper_id)
      anniversary = Anniversary.unscoped.find(@payment.anniversary_id)
      anniversary.update(has_seedmoney_payment: true)
      user = @payment.anniversary.user
      user.update(role: "sponsor")
    elsif payment_type[1] == "temporary"
      @payment = Payment.create(price: t.price,
                                anniversary_id: t.anniversary_id,
                                tid: t.tid,
                                result_code: t.result_code,
                                payment_type: t.payment_type,
                                nickname: t.nickname,
                                bill_name: t.bill_name,
                                bill_address: t.bill_address,
                                bill_phone: t.bill_phone,
                                ssn: t.ssn,
                                helper_id: t.helper_id,
                                buyeremail: t.buyeremail)
    end
    t.payment_id = @payment.id

    if t.save
      if t.result_code == "00"
        redirect_to @payment
      else
        render nothing: true
      end
    else
      logger.info t.errors
      render 'new'
    end

    # mtrn.payment_id = p_noti["payment_id"]
    # mtrn.document_id = p_noti["document_id"]
    # mtrn.p_mid = params[:p_mid]
    # mtrn.p_status = params[:p_status]
    # mtrn.p_type = params[:p_type]
    # mtrn.p_auth_dt = params[:p_auth_dt]
    # mtrn.moid = params[:p_oid]
    # mtrn.p_fn_cd1 = params[:p_fn_cd1]
    # mtrn.p_fn_cd2 = params[:p_fn_cd2]
    # mtrn.p_fn_nm = params[:p_fn_nm]
    # mtrn.p_amt = params[:p_amt]
    # mtrn.p_uname = params[:p_uname]

app/helpers/payments_helper.rb
module PaymentsHelper
  def getPayResult(code)
    case code
      when "00"
        rtn_message = "결제완료"
      when "01"
        rtn_message = "오류"
      else
        rtn_message = ""
    end

    rtn_message
  end

  # inicis결제 코드값 가져오기
  def getPaymentCodeTitle(colname, code)
    rtnTitle = ""

    case colname
      when "transaction.result_code"
        codehash = { "00" => "성공", "01" => "결제오류" }
      when "transaction.pay_method"
        codehash = { "VCard" => "신용카드(ISP)", "Card" => "신용카드(안심클릭)", "DirectBank" => "실시간계좌이체", "HPP" => "핸드폰", "VBank" => "무통장입금(가상계좌)" }
      when "transaction.card"
        codehash = { "01"=>"외환", "03"=>"롯데", "04"=>"현대", "06"=>"국민", "11"=>"BC", "12"=>"삼성", "14"=>"신한", "15"=>"한미",
          "16"=>"NH", "17"=>"하나 SK", "21"=>"해외비자", "22"=>"해외마스터", "23"=>"JCB", "24"=>"해외아멕스", "25"=>"해외다이너스" }
      when "transaction.bank_code"
        codehash = { "03"=>"기업", "04"=>"국민", "05"=>"외환", "07"=>"수협중앙회", "11"=>"농협중앙회", "20"=>"우리은행", "23"=>"SC제일은행", "31"=>"대구은행",
          "32"=>"부산은행", "34"=>"광주은행", "37"=>"전북은행", "39"=>"경남은행", "53"=>"한국씨티은행", "71"=>"우체국", "81"=>"하나은행", "88"=>"신한은행" }
      when "mtransaction.p_status"
        codehash = { "00" => "성공", "01" => "결제오류" }
      when "mtransaction.p_type"
        codehash = { "ISP" => "신용카드 ISP", "CARD" => "신용카드 안심클릭", "VBANK" => "가상계좌", "BANK" => "계좌이체" }
      else
        codehash = { code => code }
    end

    rtnTitle = codehash[code]
    rtnTitle
  end
end

app/views/payments/_inicis_form.html.erb
<form action="/documents/paid_guests" class="new_paid_guest" id="new_paid_guest" method="post">
  <input type="hidden" name="buyername" value=<%= @paid_user["name"] %>>
  <input type="hidden" name="buyertel" value=<%= @paid_user["phone"] %>>
  <input type="hidden" name="buyeremail" value=<%= @paid_user["email"] %>>

  <input type=hidden name=price value=<%= @document_data["fee"]["0"]["amount"] %>>
  <input type=hidden name=mid value=<%= ENV['INICIS_ID'] %>>
  <input type=hidden name=goodname value=<%= @document_form.name.gsub(/[^\p{Word}]/, '') %>>

  <input type='hidden' name=currency value="WON">
  <input type='hidden' name=acceptmethod value="Card:DirectBank:VBank">
  <input type='hidden' name=gopaymethod value="">
  <input type='hidden' name=oid value=<%= generate_unique_oid("["+@document_form.name+"]-"+@document.id.to_s) %>>

  <input type='hidden' name=ini_encfield value=>
  <input type='hidden' name=ini_certid value=>

  <input type='hidden' name=quotainterest value="">
  <input type='hidden' name=paymethod value="">
  <input type='hidden' name=cardcode value="">
  <input type='hidden' name=cardquota value="">
  <input type='hidden' name=rbankcode value="">
  <input type='hidden' name=reqsign value="DONE">
  <input type='hidden' name=encrypted value="">
  <input type='hidden' name=sessionkey value="">
  <input type='hidden' name=uid value="">
  <input type='hidden' name=sid value="">
  <input type='hidden' name=version value=5000>
  <input type='hidden' name=clickcontrol value="">

  <input type='hidden' name=document_id value="<%= @document.id %>">

  <!-- <input type='submit'>-->
</form>

app/views/payments/_inicis_form_mobile.html.erb
<form class="new_paid_guest" id="new_paid_guest" accept-charset="euc-kr" method="post" onsubmit="document.charset='euc-kr';">
  <input type="hidden" name="P_OID" value=<%= generate_unique_oid("") %>>
  <input type="hidden" name="P_MID" value="<%= ENV['INICIS_MID']%>">
  <input type="hidden" name="P_AMT" value="<%= @document_data["fee"]["0"]["amount"] %>">
  <input type="hidden" name="P_UNAME" value="<%= @paid_user["name"] %>">
  <input type="hidden" name="P_GOODS" value="<%= @document_form.name.gsub(/[^\p{Word}]/, '') %>">
  <input type="hidden" name="P_MOBILE" value="<%= @paid_user["phone"] %>">
  <input type="hidden" name="P_EMAIL" value="<%= @paid_user["email"] %>">

  <input type="hidden" name="P_HPP_METHOD" value="2">

  <input type=hidden name="P_NEXT_URL" value="//<%= "#{request.host}" %>/payment/result">
  <input type=hidden name="P_NOTI_URL" value="//<%= "#{request.host}" %>/payment/rnoti">

</form>

app/views/payments/_inicis_form_user.html.erb
<form action="/payments" class="new_paid_guest" id="new_paid_guest" method="post">
  <input type="hidden" name="buyername" value="">
  <input type="hidden" name="buyertel" value="">
  <input type="hidden" name="buyeremail" value="">

  <input type=hidden name=price value="">
  <input type=hidden name=mid value="<%= ENV['INICIS_ID']%>">
  <input type=hidden name=goodname value="">

  <input type='hidden' name=currency value="WON">
  <input type='hidden' name=acceptmethod value="Card:DirectBank:HPP(2)">
  <input type='hidden' name=gopaymethod value="Card:DirectBank:HPP">
  <input type='hidden' name=oid value=<%= generate_unique_oid("") %>>

  <input type='hidden' name=ini_encfield value=>
  <input type='hidden' name=ini_certid value=>

  <input type='hidden' name=quotainterest value="">
  <input type='hidden' name=paymethod value="">
  <input type='hidden' name=cardcode value="">
  <input type='hidden' name=cardquota value="">
  <input type='hidden' name=rbankcode value="">
  <input type='hidden' name=reqsign value="DONE">
  <input type='hidden' name=encrypted value="">
  <input type='hidden' name=sessionkey value="">
  <input type='hidden' name=uid value="">
  <input type='hidden' name=sid value="">
  <input type='hidden' name=version value=5000>
  <input type='hidden' name=clickcontrol value="">

  <input type='hidden' name=payment_type value="<%= params[:payment_type] %>">
  <input type='hidden' name=anniversary_id value="<%= params[:anniversary_id] %>">
  <input type='hidden' name=bill_name value="">
  <input type='hidden' name=bill_address value="">
  <input type='hidden' name=bill_phone value="">
  <input type='hidden' name=ssn value="">

  <input type="hidden" name=nickname>

  <!-- <input type='submit'>-->
</form>

app/views/payments/_inicis_form_user_mobile.html.erb
<form name="new_paid_guest" class="new_paid_guest" id="new_paid_guest" accept-charset="euc-kr" method="post" onsubmit="document.charset='euc-kr';">
  <input type="hidden" name="P_OID" value=<%= generate_unique_oid("") %>>
  <input type="hidden" name="P_MID" value="<%= ENV['INICIS_MID']%>">
  <input type="hidden" name="P_AMT" value="">
  <input type="hidden" name="P_UNAME" value="">
  <input type="hidden" name="P_GOODS" value="">
  <input type="hidden" name="P_MOBILE" value="">
  <input type="hidden" name="P_EMAIL" value="">

  <input type="hidden" name="P_HPP_METHOD" value="2">

  <input type="hidden" name="P_NOTI" value="">

  <input type=hidden name="P_NEXT_URL" value="<%= paid_users_payments_url%>">
  <input type=hidden name="P_RETURN_URL" value="<%= result_payments_url(anni_id: @anniversary.id, helper_id: (@bank_helper.present? ? @bank_helper.id : 'nil') ) %>">
  <input type=hidden name="P_NOTI_URL" value="<%= rnoti_payments_url %>">

</form>

app/views/payments/order.html.erb
<div class="contents" style="background: whitesmoke">
  <div class="container attestation bg">
    <div id="join_wrapper" style="margin:40px auto;">
      <h2>결제하기</h2>

      <hr>
      <div id="join_left" class="join_left">
          <table id="user_form_table" class="tbody">
            <tr>
              <th>결제금액</th>
              <td>
                <%= text_field :pay, :amount, :value => "3000", :placeholder => "예) 250000 ", :class => "text" %>
              </td>
            </tr>

            <tr>
              <th></th>
              <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( <span id="pay_amount_kr"></span> 원 )</td>
            </tr>

            <tr>
              <th></th>
              <td></td>
            </tr>

            <tr>
              <th>이름</th>
              <td>
                <%= text_field :pay, :name, :value => "test", :placeholder => "예) 홍길동 ", :class => "text" %>
              </td>
            </tr>

            <tr>
              <th></th>
              <td></td>
            </tr>

            <tr>
              <th>전화번호</th>
              <td>
                <%= text_field :pay, :tel, :value => "010-123-1234", :placeholder => "예) 010-1234-5678 ", :class => "text" %>
              </td>
            </tr>
            <tr>
              <th></th>
              <td></td>
            </tr>
            <tr>
              <th>서비스명</th>
              <td>
                <%= text_field :pay, :service, :value => "test", :placeholder => "예) 지급명령신청 ", :class => "text" %>
              </td>
            </tr>
            <tr>
              <th></th>
              <td></td>
            </tr>
            <tr>
              <th>이메일</th>
              <td>
                <%= text_field :pay, :email, :value => "test@test.com", :placeholder => "예) hello@example.com", :class => "text" %> <%= image_tag "check.png", :class => "check", :id => 'email_check', :style => "display:none;" %>
              </td>
            </tr>
            <tr>
              <th></th>
              <td>
                <div id="email_error" style="color:red;font-size:10pt;display:none;" class="join-error">
                  이메일 형식이 올바르지 않습니다.
                  (예 : example@example.com)
                </div>
                <div id="email_correct" style="color:green;font-size:10pt;display:none;float:right;"class="join-error">
                  사용가능한 이메일 입니다.
                </div>
              </td>
            </tr>

            <% if browser.mobile? %>
              <tr>
                <th>결제방법</th>
                <td>
                  <%= radio_button_tag :pay_method, "CARD" %> 신용카드
                  <%= radio_button_tag :pay_method, "BANK" %> 계좌이체
                  <%= radio_button_tag :pay_method, "VBANK" %> 가상계좌
                </td>
              </tr>
            <% end %>

          </table>


          <div id="join_btn_box">
            <a class="regi_button" href="#">결제하기</a>
          </div>

          <div id="join_right">
            <a class="regi_button go_home" href="/">홈으로</a>
          </div>
      </div>


    </div>
  </div>
</div>

<%= render (browser.mobile? && "inicis_form_user_mobile" || "inicis_form_user") %>
<%= render "inicis_javascript" %>

<script type="text/javascript">
  $(function(){

    $('#join_btn_box .regi_button').click(function(e){
      if(!chk_value("#pay_amount")) return false;
      if(!chk_value("#pay_name")) return false;
      if(!chk_value("#pay_tel")) return false;
      if(!chk_value("#pay_service")) return false;
      if(!chk_value("#pay_email")) return false;

<% if browser.mobile? %>
      var wallet = window.open("", "BTPG_WALLET");

      $('input[name="P_UNAME"]').val( $("#pay_name").val() );
      $('input[name="P_MOBILE"]').val( $("#pay_tel").val() );
      $('input[name="P_EMAIL"]').val( $("#pay_email").val() );
      $('input[name="P_AMT"]').val( $("#pay_amount").val() );
      $('input[name="P_GOODS"]').val( $("#pay_service").val() );

      switch( $('input[name="pay_method"]:checked').val() ) {
        case "CARD" : // 신용카드
          tURL = "https://mobile.inicis.com/smart/wcard/";
          break;
        case "VBANK" : // 가상계좌
          tURL = "https://mobile.inicis.com/smart/vbank/";
          break;
        case "BANK" : // 계좌이체
          tURL = "https://mobile.inicis.com/smart/bank/";
          break;
      }

      mForm = $('.new_paid_guest')[0];
      mForm.target = "BTPG_WALLET";
      mForm.action = tURL;
      mForm.submit();
<% else %>
      $('input[name="buyername"]').val( $("#pay_name").val() );
      $('input[name="buyertel"]').val( $("#pay_tel").val() );
      $('input[name="buyeremail"]').val( $("#pay_email").val() );
      $('input[name="price"]').val( $("#pay_amount").val() );
      $('input[name="goodname"]').val( $("#pay_service").val() );

      inicisPayment($('.new_paid_guest')[0]);
      // for inicis flash module
      e.preventDefault();
<% end %>

    });

    $("#pay_amount").keyup(function() {
      $("#pay_amount_kr").html( number_to_hangul2($("#pay_amount").val()) );
    });

    $('#btn-back').click(function() {
      location.href = "/";
    });
  });

  //숫자를 만 단위 한글로 예) 12300 -> 1만 2300
  function number_to_hangul2(string)
  {
    var result = "";
    var number = parseInt(string);
    var hj = new Array("","만","억","조","경","해","시","양","구","간","정","재","극");
    var i=0;

    while (number > 0){
      var rest = String(number % 10000);
      number = parseInt(number / 10000);
      if (rest > 0)
        result = rest + hj[i] + " " + result;
      i++;
    }

    return $.trim(result);
  }

  function chk_value(objname) {
    if( !$(objname).val() ) {
      alert("값을 입력하셔야 합니다.");
      $(objname).focus();

      return false;
    } else {
      return true;
    }
  }
</script>

app/views/payments/result.html.haml
.page-wrapper
  .container
    .content-box
      .content-box__title
        - if @transaction.present?
          계좌이체가 #{@transaction.result_msg}
        - else
          계좌이체가 정상적으로 진행되지 않았습니다.
      .content-box__field
        = link_to '후원나무 페이지 가기', anniversary_path(id: params[:anni_id])

app/views/payments/rnoti.html.haml
OK

app/views/payments/show.html.haml
.page-wrapper
  .container
    - if @payment.payment_type == "seedmoney"
      .content-box
        .content-box__title 결제완료
        .content-box__field.content-box__field-margin.text-center
          %h3
            %b
              후원나무 페이지 생성이 완료되었습니다.
          %h4{:style => 'margin-top: 10px'}
            나의 후원나무 페이지를 확인 하세요!
          = link_to image_tag('btn-show-my.png'), @payment.anniversary, class: 'btn-mypage'

          .text-center
            %a.btn-mainpage{:href => '/'}
              %h5 &gt; 메인으로 이동하기

        %hr{:style => 'border-color: #808080'}
        .content-box__field.content-box__field-margin.text-center
          %h3
            %b
              후원나무 성장시키는 방법
          .content-box__field-img-row
            = image_tag 'tree-step.png'
          .content-box__field-img-row.mobile
            = image_tag 'tree-step-mobile.png'
          / %p
          /   * 나만의 페이지를 지인들에게 공유하시고 후원나무를 함께 키워보세요.
          /   %br
          /   * 지인들의 댓글과 공유 만으로도 더 큰 나눔을 할 수 있습니다.
    - elsif @payment.payment_type == "temporary"
      .content-box
        .content-box__title 일시후원이 완료되었습니다.
        .content-box__field
          = link_to '후원나무 페이지 가기', @payment.anniversary